### ISSUE TITLE
Add the loading icon when the user clicks on the find match button

### ISSUE THREAD

**Issue by yahuiliang** [superyang713/ETL#2]
Please switch the button below into an icon which presents loading when the user clicks on it:
![screen shot 2019-02-20 at 1 39 17 pm](https://user-images.githubusercontent.com/31673419/53119398-02425e00-3515-11e9-9088-a03b9e971b84.png)
When the user gets matched with another person, the icon should be switched back to "FIND A MATCH".

**Comment by yahuiliang** [comment]
The link to the pull request: https://github.com/superyang713/ETL/pull/5.

**Comment by yahuiliang** [comment]
The feature is done.

**Comment by superyang713** [comment]
Good job
